README.md, packages/path_provider/.gitignore, packages/path_provider/CHANGELOG.md, packages/path_provider/LICENSE, packages/path_provider/README.md, packages/path_provider/example/.gitignore, packages/path_provider/example/README.md, packages/path_provider/example/elinux/CMakeLists.txt, packages/path_provider/example/elinux/flutter/CMakeLists.txt, packages/path_provider/example/elinux/flutter/generated_plugin_registrant.h, packages/path_provider/example/elinux/flutter/generated_plugins.cmake, packages/path_provider/example/elinux/runner/CMakeLists.txt, packages/path_provider/example/elinux/runner/command_options.h, packages/path_provider/example/elinux/runner/flutter_embedder_options.h, packages/path_provider/example/elinux/runner/flutter_window.cc, packages/path_provider/example/elinux/runner/flutter_window.h, packages/path_provider/example/elinux/runner/main.cc, packages/path_provider/example/integration_test/path_provider_test.dart, packages/path_provider/example/lib/main.dart, packages/path_provider/example/pubspec.yaml, packages/path_provider/example/test_driver/integration_test.dart, packages/path_provider/lib/path_provider_elinux.dart, packages/path_provider/pubspec.yaml, packages/path_provider/test/path_provider_elinux_test.dart
See: https://github.com/sony/flutter-elinux-plugins/issues/9
=> Add path_provider for elinux

packages/path_provider/README.md, packages/video_player/README.md
=> Fix wrong path in pubspec.yaml

packages/path_provider/README.md, packages/video_player/README.md
=> Update README: fix wrong pubspec.yaml

packages/shared_preferences/.gitignore, packages/shared_preferences/CHANGELOG.md, packages/shared_preferences/README.md, packages/shared_preferences/example/.gitignore, packages/shared_preferences/example/README.md, packages/shared_preferences/example/elinux/.gitignore, packages/shared_preferences/example/elinux/CMakeLists.txt, packages/shared_preferences/example/elinux/flutter/CMakeLists.txt, packages/shared_preferences/example/elinux/flutter/generated_plugin_registrant.h, packages/shared_preferences/example/elinux/flutter/generated_plugins.cmake, packages/shared_preferences/example/elinux/flutter/main.dart, packages/shared_preferences/example/elinux/runner/CMakeLists.txt, packages/shared_preferences/example/elinux/runner/command_options.h, packages/shared_preferences/example/elinux/runner/flutter_embedder_options.h, packages/shared_preferences/example/elinux/runner/flutter_window.cc, packages/shared_preferences/example/elinux/runner/flutter_window.h, packages/shared_preferences/example/elinux/runner/main.cc, packages/shared_preferences/example/integration_test/shared_preferences_test.dart, packages/shared_preferences/example/lib/main.dart, packages/shared_preferences/example/pubspec.yaml, packages/shared_preferences/example/test_driver/integration_test.dart, packages/shared_preferences/lib/shared_preferences_elinux.dart, packages/shared_preferences/pubspec.yaml, packages/shared_preferences/test/shared_preferences_elinux_test.dart
Added shared_preferences_elinux
=> Add shared_preferences

packages/video_player/README.md
=> Update README: fix pubspec.yaml

packages/path_provider/example/elinux/.gitignore, packages/path_provider/example/elinux/CMakeLists.txt, packages/path_provider/example/elinux/flutter/CMakeLists.txt, packages/path_provider/example/elinux/runner/CMakeLists.txt, packages/shared_preferences/example/elinux/CMakeLists.txt, packages/shared_preferences/example/elinux/flutter/CMakeLists.txt, packages/shared_preferences/example/elinux/runner/CMakeLists.txt, packages/video_player/elinux/CMakeLists.txt, packages/video_player/example/elinux/CMakeLists.txt, packages/video_player/example/elinux/flutter/CMakeLists.txt, packages/video_player/example/elinux/runner/CMakeLists.txt
Merged from flutter-elinux (https://github.com/sony/flutter-elinux/pull/43)
=> Merge the latest app template from flutter-elinux

packages/video_player/CHANGELOG.md, packages/video_player/elinux/gst_video_player.cc, packages/video_player/elinux/gst_video_player.h, packages/video_player/example/elinux/runner/flutter_embedder_options.h, packages/video_player/pubspec.yaml
Release version 0.9.1
- Temporarily disable auto-repeat
- Update the elinux template of the example app
=> [Video player] Temporarily disable auto-repeat

packages/video_player/elinux/gst_video_player.cc, packages/video_player/elinux/video_player_elinux_plugin.cc
Improved an error handling when getting current position.
=> [video_player] Improve error handling

packages/video_player/CHANGELOG.md, packages/video_player/elinux/gst_video_player.cc, packages/video_player/elinux/gst_video_player.h, packages/video_player/pubspec.yaml
=> [video_player] Add missing mutex

packages/video_player/pubspec.yaml
Fixed wrong repo path of video_player.
=> [video_player] Fix wrong repo path

packages/video_player/elinux/CMakeLists.txt, packages/video_player/elinux/gst_video_player.cc
I removed unnecessary header file includes and libraries.
=> [video_palyer] Remove unused includes and libraries

packages/video_player/elinux/messages/create_message.h
=> [video_player] Fix a typo

packages/video_player/README.md
=> [video_player] Update README: required libraries

README.md
https://github.com/sony/flutter-elinux-plugins/issues/6
=> Update README: add camera plugin

packages/camera/elinux/CMakeLists.txt
This is just refactoring of CMakeLists.txt.
=> [camera] refactor CMakeLists.txt

packages/camera/README.md
=> [camera] update README

packages/video_player/example/elinux/CMakeLists.txt
I changed the binary name to match the project name.
=> [video_player] change binary name

packages/camera/CHANGELOG.md, packages/camera/README.md, packages/camera/elinux/camera_elinux_plugin.cc, packages/camera/elinux/channels/method_channel_device.cc, packages/camera/pubspec.yaml
Fixed the bug. See: https://github.com/sony/flutter-elinux-plugins/issues/6#issuecomment-901698667
Also, I changed the camera type from back-camera to external-camera.
=> [camera] Fix wrong orientation

packages/video_player/elinux/video_player_elinux_plugin.cc
Improved flutter project asset path.
=> [video_player] improve asset path

packages/camera/README.md, packages/video_player/README.md
Added the description about customization of `videoconvert` element.
=> Update README: add description about customization of videoconvert

README.md, packages/joystick/.gitignore, packages/joystick/CHANGELOG.md, packages/joystick/LICENSE, packages/joystick/README.md, packages/joystick/elinux/.gitignore, packages/joystick/elinux/CMakeLists.txt, packages/joystick/elinux/include/joystick/joystick_plugin.h, packages/joystick/elinux/joystick_plugin.cc, packages/joystick/elinux/linux_joystick.cc, packages/joystick/example/.gitignore, packages/joystick/example/README.md, packages/joystick/example/elinux/.gitignore, packages/joystick/example/elinux/CMakeLists.txt, packages/joystick/example/elinux/flutter/CMakeLists.txt, packages/joystick/example/elinux/flutter/generated_plugin_registrant.h, packages/joystick/example/elinux/flutter/generated_plugins.cmake, packages/joystick/example/elinux/runner/CMakeLists.txt, packages/joystick/example/elinux/runner/command_options.h, packages/joystick/example/elinux/runner/flutter_embedder_options.h, packages/joystick/example/elinux/runner/flutter_window.cc, packages/joystick/example/elinux/runner/flutter_window.h, packages/joystick/example/elinux/runner/main.cc, packages/joystick/example/lib/main.dart, packages/joystick/example/pubspec.yaml, packages/joystick/lib/joystick.dart, packages/joystick/pubspec.yaml
I implemented the joystick plugin (dart::ffi version).
https://github.com/sony/flutter-elinux-plugins/issues/35
=> Add joystick plugin

packages/path_provider/pubspec.yaml
Remove use of deprecated pedantic package
=> [path_provider] Remove use of deprecated pedantic package

packages/video_player/CHANGELOG.md, packages/video_player/elinux/gst_video_player.h, packages/video_player/pubspec.yaml
Fixed https://github.com/sony/flutter-elinux-plugins/issues/50
Signed-off-by: Hidenori.Matsubayashi <hidenori.matsubayashi@gmail.com>
=> [video-player] Fix missing include

packages/path_provider/CHANGELOG.md, packages/path_provider/example/elinux/CMakeLists.txt, packages/path_provider/example/elinux/runner/command_options.h, packages/path_provider/example/elinux/runner/flutter_embedder_options.h, packages/path_provider/example/elinux/runner/main.cc, packages/path_provider/example/pubspec.yaml, packages/path_provider/pubspec.yaml
=> [path_provider] update for flutter 3.3.0 release

packages/joystick/CHANGELOG.md, packages/joystick/elinux/joystick_plugin.cc, packages/joystick/elinux/linux_joystick.cc, packages/joystick/example/elinux/CMakeLists.txt, packages/joystick/example/elinux/runner/command_options.h, packages/joystick/example/elinux/runner/flutter_embedder_options.h, packages/joystick/example/elinux/runner/main.cc, packages/joystick/example/pubspec.yaml, packages/joystick/lib/joystick.dart, packages/joystick/pubspec.yaml
=> [joystick] update for flutter 3.3.0 release

packages/camera/CHANGELOG.md, packages/camera/README.md, packages/camera/example/elinux/CMakeLists.txt, packages/camera/example/elinux/runner/command_options.h, packages/camera/example/elinux/runner/flutter_embedder_options.h, packages/camera/example/elinux/runner/main.cc, packages/camera/example/lib/main.dart, packages/camera/example/pubspec.yaml, packages/camera/pubspec.yaml
=> [camera] update for camera ^0.10.0+1 / flutter 3.3.0 release

packages/camera/elinux/camera_elinux_plugin.cc
=> camera: enable stream image APIs

packages/camera/CHANGELOG.md, packages/camera/pubspec.yaml
=> camera: update to version 0.3.0

README.md, packages/path_provider/CHANGELOG.md, packages/path_provider/example/integration_test/path_provider_test.dart, packages/path_provider/example/lib/main.dart, packages/path_provider/example/pubspec.yaml, packages/path_provider/lib/src/get_application_id.dart, packages/path_provider/lib/src/get_application_id_real.dart, packages/path_provider/lib/src/get_application_id_stub.dart, packages/path_provider/lib/src/path_provider_elinux.dart, packages/path_provider/pubspec.yaml, packages/path_provider/test/path_provider_elinux_test.dart
Update for path_provider 2.2.0
https://github.com/flutter/packages/tree/main/packages/path_provider
=> path_provider: update for official packages/path_provider 2.2.0

packages/camera/example/elinux/runner/flutter_embedder_options.h, packages/camera/example/elinux/runner/main.cc, packages/joystick/example/elinux/runner/flutter_embedder_options.h, packages/joystick/example/elinux/runner/main.cc, packages/path_provider/example/elinux/runner/flutter_embedder_options.h, packages/path_provider/example/elinux/runner/main.cc, packages/shared_preferences/example/elinux/runner/flutter_embedder_options.h, packages/shared_preferences/example/elinux/runner/main.cc, packages/video_player/example/elinux/runner/flutter_embedder_options.h, packages/video_player/example/elinux/runner/main.cc
This change updates elinux template source files in examples.
=> examples: update elinux template source files

packages/video_player/CHANGELOG.md, packages/video_player/example/pubspec.yaml, packages/video_player/pubspec.yaml
This change updates flutter and dart-sdk versions in pubspec.yaml for flutter 3.13.0
Related issue: #78
=> video-player: update flutter/dart-sdk versions in pubspec.yaml

packages/camera/CHANGELOG.md, packages/camera/elinux/camera_elinux_plugin.cc, packages/camera/elinux/channels/method_channel_camera.cc, packages/camera/elinux/channels/method_channel_device.cc, packages/camera/lib/camera_elinux.dart, packages/camera/lib/src/elinux_camera.dart, packages/camera/lib/src/type_conversion.dart, packages/camera/lib/src/utils.dart, packages/camera/pubspec.yaml
Fixed https://github.com/sony/flutter-elinux/issues/211
=> camera: add ELinuxCamera dartPluginClass

packages/video_player/README.md
This change upgrades video_player version to v2.6.1 in readme.
=> video_player: update readme

packages/video_player/elinux/video_player_elinux_plugin.cc
App sometimes crashes when calling `VideoPlayerController.dispose()`. You can replicate it by creating a new `VideoPlayerController()` -> `play()` -> `dispose()` a few times.
Happens here (player is null): https://github.com/sony/flutter-elinux-plugins/blob/1495f166fc6f3def93f4ca24583e67b505318990/packages/video_player/elinux/video_player_elinux_plugin.cc#L336
Fixed by calling `texture_registrar_->UnregisterTexture(texture_id);` first before disposing the player.
I also encapsulated the disposing logic into its own function to avoid code duplication.
=> [video_player] Fix crash on dispose.

packages/video_player/elinux/gst_video_player.cc, packages/video_player/elinux/gst_video_player.h
Added some missing gst unrefs.
I think `pixels_` type was wrong too.
=> [video_player] Free resources
